
posttrain: 
  module: 
    checkpoint_path: "checkpoints/pretrain/last.ckpt"
    val_sparsity: 0.4

    agg_name: boq
    agg_init_kwargs: {}

    lr: 0.0002
    weight_decay: 0.0001
    warmup_steps: 250


  data: 
    #train_data_dir: "/home/oliver/datasets_drive/vpr_datasets/gsv-cities/" 
    #val_data_dir: "/home/oliver/datasets_drive/vpr_datasets"
    #train_data_dir: "/Users/olivergrainge/github/Datasets/gsv-cities/"
    #val_data_dir: "/Users/olivergrainge/github/Datasets/"
    train_data_dir: "/home/oliver/datasets_drive/vpr_datasets/gsv-cities/"
    val_data_dir: "/home/oliver/datasets_drive/vpr_datasets"
    batch_size: 128
    img_per_place: 4
    min_img_per_place: 4
    shuffle_all: False
    image_size:
      - 224
      - 224
    num_workers: 12
    val_set_names:
      - pitts30k

  trainer:
    max_epochs: 6
    accelerator: "auto"
    devices: "auto"
    precision: "16-mixed"
    num_sanity_val_steps: 0
    log_every_n_steps: 10
