
posttrain: 
  module: 
    model_name: ViT
    checkpoint_path: ""

    model_init_args:
      image_size: 224
      patch_size: 16
      dim: 384
      depth: 4   
      heads: 6   
      mlp_dim: 1536 
      in_channels: 3
      dim_head: 64
      dropout: 0.1  
      emb_dropout: 0.1
      embedding_norm: "LayerNorm"
      embedding_linear: "Linear"
      attention_linear_layer: "Linear"
      attention_norm_layer: "LayerNorm"
      feedforward_linear_layer: "Linear"
      feedforward_norm_layer: "LayerNorm"
      feedforward_activation_layer: "GELU"

  data: 
    train_data_dir: "/Users/olivergrainge/github/Datasets/gsv-cities/" 
    val_data_dir: "/Users/olivergrainge/github/Datasets"
    batch_size: 6
    img_per_place: 4
    min_img_per_place: 4
    shuffle_all: False
    image_size:
      - 224
      - 224
    num_workers: 0
    val_set_names:
      - pitts30k

  trainer:
    max_epochs: 1 
    accelerator: "auto"
    devices: "auto"
    precision: 32
    num_sanity_val_steps: 0
