
model: 
  checkpoint_path: checkpoints/config-epoch=0-lateral_loss=58.44-frontal_loss=59.17.ckpt

eval_module: 
  val_dataset_dir: /home/oliver/datasets_drive/vpr_datasets
  dataset_names:
    - pitts30k
    - nordland
  image_size: 224
  batch_size: 128
  num_workers: 16
  match_gpu: False
