
baseline: 
  baseline_name: eigenplaces

eval_module: 
  val_dataset_dir: /home/oliver/datasets_drive/vpr_datasets
  dataset_names:
    - pitts30k
    - nordland
  image_size: 512
  batch_size: 128
  num_workers: 16
  match_gpu: False