
model: 
  checkpoint_path: checkpoints/resnet34-cosplace-epoch=1-val_recall@1=36.84.ckpt

eval_module: 
  val_dataset_dir: /home/oliver/datasets_drive/vpr_datasets
  dataset_names:
    - pitts30k
    - nordland
  image_size: 224
  batch_size: 128
  num_workers: 16
  match_gpu: False
