
eval: 
  checkpoint_path: "checkpoints/posttrain/cls/cls_epoch=0-val_recall=86.3556.ckpt"

  evaluate_module:  
    #val_data_dir: "/home/oliver/datasets_drive/vpr_datasets"
    #val_data_dir: "/Users/olivergrainge/github/Datasets/"
    val_data_dir: "/home/oliver/datasets_drive/vpr_datasets"
    val_set_names:
      #- pitts30k 
      #- msls 
      #- tokyo247
      #- eynsham 
      - svox_night 
      - svox_sun 
      - svox_snow 
      - svox_overcast  
      - svox_rain 
    image_size: 224
    batch_size: 64
    num_workers: 8

  trainer: 
    accelerator: "auto"
    precision: "16-mixed"
    max_epochs: 1 

