
eval: 
  model_module: 
    checkpoint_path: "checkpoints/posttrain/ViT/fp_config_epoch=0-val_recall=0.8661.ckpt"

  evaluate_module: 
    val_dataset_dir: "/home/oliver/datasets_drive/vpr_datasets/"
    val_set_names: 
      - pitts30k
      - nordland 
      - msls 

    image_size: 224
    batch_size: 64
    num_workers: 8

  trainer: 
    max_epochs: 50
    accelerator: "auto"
    devices: "auto"
    precision: 16