
model: 
  model_name: BoQModel
  model_init_args: 
    image_size: 224
    patch_size: 16
    dim: 768
    depth: 12
    heads: 12
    mlp_dim: 3072
    in_channels: 3
    dim_head: 64
    dropout: 0.0
    emb_dropout: 0
    embedding_norm: LayerNorm
    embedding_linear: Linear
    attention_linear_layer: Linear
    attention_norm_layer: LayerNorm
    feedforward_linear_layer: Linear
    feedforward_norm_layer: LayerNorm
    feedforward_activation_layer: GELU
    proj_channels: 512
    num_queries: 32
    num_layers: 2
    row_dim: 32

  # training parameters
  data_dir: /home/oliver/datasets_drive/vpr_datasets/sf_xl/raw/panoramas
  val_dataset_dir: /home/oliver/datasets_drive/vpr_datasets/sf_xl/processed/val
  image_size: 224
  iterations_per_epoch: 200
  M: 15
  N: 3
  focal_dist: 10
  min_images_per_class: 5
  visualize_classes: 0
  groups_num: 9 # N * N
  batch_size: 128
  num_workers: 8
  fc_output_dim: 16384
  s: 100
  m: 0.4
  classifiers_lr: 0.01
  model_lr: 0.00001
  lambda_lat: 1.0
  lambda_front: 1.0
  
trainer: 
  max_epochs: 1000
  accelerator: auto
  precision: 32
  reload_dataloaders_every_n_epochs: 1
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  limit_train_batches: 500



